import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Form from './form' // Formulário

export default function Home() {
  
  return (
    
    <div className={styles.container}>
      <Head>
        <title>Doação de Computadores Usados</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Doação de computadores usados
        </h1>

        <h2>Formulário de Doação</h2>
      
        <Form></Form> {/* Formulário */}

      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/FelipeBMost"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <h2 id="easterEgg" className={styles.logo}>
            Pura força de vontade
          </h2>
        </a>
      </footer>
    </div>
    
  )
}
